System/Webserver/ca_webserver/ca_webserver/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls', namespace='home')),
    url(r'^info_display/', include('info_display.urls', namespace='info_display')),
    url(r'^admin/', admin.site.urls),
]

System/Webserver/ca_webserver/home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

System/Webserver/ca_webserver/info_display/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^welcome/$', views.welcome, name='welcome'),
    url(r'^display_user_info/$', views.display_user_info, name='display_user_info'),
    url(r'^display_admin_info/$', views.display_admin_info, name='display_admin_info'),
    url(r'^goodbye/$', views.all_logout, name='goodbye'),
    url(r'^new/$', views.new, name='new'),
    url(r'^crl/$', views.crl, name='crl'),
    url(r'^revoke_all/$', views.revoke_all, name='revoke_all'),
    url(r'^revoke_single/$', views.revoke_single, name='revoke_single'),
    url(r'^wonderland/$', views.wonderland, name='wonderland'),
]

System/Webserver/ca_webserver/info_display/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    uid = models.CharField(max_length=10)
    lastname = models.CharField(max_length=50)

    def __str__(self):
        return self.lastname

System/Webserver/ca_webserver/info_display/forms.py
from django import forms

class UserLoginForm(forms.Form):
    user_id = forms.CharField(label='User ID', max_length=10)
    password = forms.CharField(label='Password', max_length=256, widget=forms.PasswordInput)

class GetInfoForm(forms.Form):
    user_id = forms.CharField(max_length=10, widget=forms.HiddenInput())

class UpdateInfoForm(forms.Form):
    lastname = forms.CharField(label='Lastname', max_length=256)
    firstname = forms.CharField(label='Firstname', max_length=256)
    emailAddress = forms.CharField(label='E-mail address', max_length=256)
    password = forms.CharField(label='Password', max_length=256, widget=forms.PasswordInput)

class ActionChoiceForm(forms.Form):
    action = forms.ChoiceField(choices= [('NEW', 'Get new certificate'), ('ALL', 'Revoke all certificates')])

class ConfirmationForm(forms.Form):
        password = forms.CharField(label='Password', max_length=256, widget=forms.PasswordInput)

class SingleConfirmationForm(forms.Form):
    serial = forms.CharField(label='Serial', max_length=256)
    password = forms.CharField(label='Password', max_length=256, widget=forms.PasswordInput)

class CertificateQueryForm(forms.Form):
    username = forms.CharField(label='Username', max_length=256)
    password = forms.CharField(label='Password', max_length=256, widget=forms.PasswordInput)
    keyfile = forms.CharField(label='Keyfile', max_length=256)
    certfile = forms.CharField(label='Certfile', max_length=256)
    cafile = forms.CharField(label='CAfile', max_length=256, required=False)

System/Webserver/ca_webserver/info_display/views.py
import array
import json
import logging

import OpenSSL
import os
import pdb
import requests
import subprocess

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sessions.models import Session
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.template import loader

from .forms import UserLoginForm, UpdateInfoForm, ConfirmationForm, SingleConfirmationForm, CertificateQueryForm
from .helpers import admin_access_decorator, is_ca_admin
from .models import UserInfo

db_url = "https://192.168.50.33:8100"
ca_url = "https://192.168.50.31:8100"
ca_file = '/home/webserver/virtual_environment/ca_webserver/ssl/cacert.pem'


logger = logging.getLogger()
handler = logging.FileHandler('logs/webserver.log')
formatter = logging.Formatter('%(asctime)s %(name)-12s %(levelname)-8s %(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)
logger.setLevel(logging.INFO)

@admin_access_decorator
def index(request):

    return render(request, 'info_display/index.html')

@admin_access_decorator
def user_login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/info_display/welcome')
    #If POST request, validate input and try to authenticate via DB server
    if request.method == 'POST':
        #Create form instance from submitted data
        form = UserLoginForm(request.POST)
        #Check for validity
        if form.is_valid():
            #Perform authentication
            user = authenticate(username=form.cleaned_data['user_id'], password=form.cleaned_data['password'])
            # Debugging db connectivity
            if user is not None:
                logger.info('%s logged in' % request.user.username)
                login(request, user) #TODO not sure if login is necessary
                return HttpResponseRedirect('/info_display/welcome/')
            else:
                logger.warning('failed login attempt with uid %s' % form.cleaned_data['user_id'])
                return render(request, 'info_display/user_login.html', {'form': form, 'error_msg': 'Invalid User ID/password combination.'})

    #If not POST request, create empty form
    else:
        form = UserLoginForm()

    return render(request, 'info_display/user_login.html', {'form': form})

# def admin_login(request):
#     #If POST request, validate input and try to authenticate via DB server
#     if request.method == 'POST':
#         #Create form instance from submitted data
#         form = UserLoginForm(request.POST)
#         #Check for validity
#         if form.is_valid():
#             #Perform authentication
#             user = authenticate(username=form.cleaned_data['user_id'], password=form.cleaned_data['password'])
#             if user is not None and user.is_staff:
#                 login_preserve_backend(request, user) #TODO not sure if login is necessary
#                 return HttpResponseRedirect('/info_display/display_admin_info/')
#             else:
#                 return render(request, 'info_display/admin_login.html', {'form': form, 'error_msg': 'Invalid Certificate'})
#
#     #If not POST request, create empty form
#     else:
#         form = UserLoginForm()
#
#     return render(request, 'info_display/admin_login.html', {'form': form})

@admin_access_decorator
def welcome(request):
    if request.user.is_authenticated:
        return render(request, 'info_display/welcome.html', {'user_id': request.user.username})
    else:
        return HttpResponseRedirect('/info_display/user_login')

@admin_access_decorator
def display_user_info(request):
    if request.user.is_authenticated:
        downloadfile = False
        error_msg = False
        if request.method != 'POST':
            data_response = requests.get(("%s/users/%s" % (db_url, request.user.username)), verify=ca_file)
            if data_response.ok:
                user_data = data_response.json()
                #Set password field to prevent error
                user_data['password'] = 'Password'
                #Create form instance from retrieved data
                form = UpdateInfoForm(user_data)
                #Check for validity
                if form.is_valid():
                    error_msg = None
                else:
                    error_msg = 'Invalid data retrieved.'

            else:
                return HttpResponseRedirect('/info_display/welcome/', request)
        else:
            # Method is post, check for changes in user data
            # Create form instance from submitted data
            form = UpdateInfoForm(request.POST)
            # Check for validity
            if form.is_valid():
                data_response = requests.get(("%s/users/%s" % (db_url, request.user.username)), verify=ca_file)

                if data_response.ok:
                    user_data = data_response.json()
                    # Did changes occur?
                    if form.cleaned_data['lastname'] == user_data['lastname'] and form.cleaned_data['firstname'] == user_data['firstname'] and form.cleaned_data['emailAddress'] == user_data['emailAddress']:
                        pass
                    else:
                        # Modify user data
                        update_response = requests.post(("%s/users/%s" % (db_url, request.user.username)), data=json.dumps(form.cleaned_data), verify=ca_file)
                        if update_response.ok:
                            pass
                        else:
                            return HttpResponseRedirect('/info_display/welcome/')
                    certificate_pw = {'password': form.cleaned_data['password']}
                    certificate_response = requests.post("%s/certificates/new/%s" % (ca_url, request.user.username), data=json.dumps(certificate_pw), verify=ca_file)
                    if certificate_response.ok:
                        logger.info('%s requested a new certificate' % request.user.username)
                        cert_dict = certificate_response.json()

                        pkcs_bytes = array.array('b', cert_dict['pkcs12'])
                        file_handle = open(('info_display/files/pkcs12_%s.pfx' % request.user.username), 'wb+')
                        file_handle.truncate() # in case the last certificate was not downloaded
                        file_handle.write(pkcs_bytes)# pkcs12.export())
                        file_handle.close()
                        downloadfile = True
                    else:
                        return HttpResponseRedirect('/info_display/welcome/')
                    form = None # No need to display the form now
                    return HttpResponseRedirect('/info_display/new/', request)

                else:
                    return HttpResponseRedirect('/info_display/welcome/', request)



        return render(request, 'info_display/display_user_info.html', {'form': form, 'error_msg': error_msg, 'downloadfile': downloadfile})
    else:
        return HttpResponseRedirect('/info_display/user_login/')

def display_admin_info(request):
    if request.user.is_authenticated and is_ca_admin(request.user):
        if request.method != 'POST':
            return render(request, 'info_display/display_admin_info.html', {'values': None,  'error_msg': None})
        else:
            logger.info('user %s successfully requested admin info' % request.user.username)
            items = ['issued', 'revoked', 'serial_number']
            values = {}

            for item in items:
                data_response = requests.get("%s/ca/%s" % (ca_url, item), verify=ca_file)
                if data_response:
                    data = data_response.json()
                    if item == 'serial_number':
                        values[item] = data['serialNumber']
                    else:
                        values[item] = data[item]
                else:
                    return render(request, 'info_display/display_admin_info.html', {'values': None, 'error_msg': 'Retrieval failed at %s' % item})

            return render(request, 'info_display/display_admin_info.html', {'values': values, 'error_msg': None})

    else:
        return HttpResponseRedirect('/info_display/user_login/')

@admin_access_decorator
def all_logout(request):
    if request.user.is_authenticated:
        user_id = request.user.username
        logger.info('%s logged out' % request.user.username)
        logout(request)

        #Forget which backend was used before
        Session.objects.all().delete()
        return render(request, 'info_display/goodbye.html', {'info_msg': 'Logged %s out successfully' % user_id})
    else:
        return render(request, 'info_display/goodbye.html', {'info_msg': 'No user was logged in...'})

@admin_access_decorator
def new(request):
    if request.user.is_authenticated:
        if request.method != 'POST':
            return render(request, 'info_display/new.html', {'error_msg': None})
        else:
            try:
                file_handle = open(('info_display/files/pkcs12_%s.pfx' % request.user.username), 'rb')
                file_data = file_handle.read()
                file_handle.close()
                os.remove('info_display/files/pkcs12_%s.pfx' % request.user.username)
                response = HttpResponse(file_data, content_type='application/octet-stream')
                response['Content-Disposition'] = 'attachment; filename="pkcs12.pfx"'
                logger.info('%s downloaded a certificate' % request.user.username)
                return response
            except IOError:
                return render(request, 'info_display/new.html', {'error_msg': "Certificate files can only be downloaded once after creation!"})
    else:
        return HttpResponseRedirect('/info_display/user_login/')

@admin_access_decorator
def revoke_all(request):
    if request.user.is_authenticated:

System/Webserver/ca_webserver/info_display/templates/info_display/admin_login.html
<h1>Administrator Login Page</h1>

  {% if error_msg %}<p><strong>{{ error_msg }}</strong></p>{% endif %}

  <form action="{% url 'info_display:admin_login' %}" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Login" />
  </form>

System/Webserver/ca_webserver/info_display/templates/info_display/crl.html
<h3>Download the certificate revocation list</h3>

{% if error_msg %}<p><strong>{{ error_msg }}</strong></p>{% endif %}
<p>
<a href="/info_display/welcome">Back to welcome</a>
</p>

<form action="{% url 'info_display:crl' %}" method="post">
{% csrf_token %}
<input type="submit" value="Download" />
</form>

<form action="{% url 'info_display:goodbye' %}" method="post">
{% csrf_token %}
<input type="submit" value="Logout" />
</form>

System/Webserver/ca_webserver/info_display/templates/info_display/display_admin_info.html
<h3>Admin display</h3>

{% if error_msg %}<p><strong>{{ error_msg }}</strong></p>{% endif %}

<form action="{% url 'info_display:display_admin_info' %}" method="post">
{% csrf_token %}
<input type="submit" value="Request values"/>
</form>

{% if values %}

<ul>
  <li>Issued certificates: {{ values.issued }}</li>
  <li>Revoked certificates: {{ values.revoked }}</li>
  <li>Current serial: {{ values.serial_number }}</li>
</ul>

{% endif %}

<form action="{% url 'info_display:goodbye' %}" method="post">
{% csrf_token %}
<input type="submit" value="Logout" />
</form>

System/Webserver/ca_webserver/info_display/templates/info_display/display_user_info.html
<p>Make changes to the user data as desired. The new certificate will incorporate these. The password
you enter here is used to encrypt the certificate file. This <strong>is not</strong> your account's
password!</p>

{% if error_msg %}<p><strong>{{ error_msg }}</strong></p>{% endif %}

{% if form %}<form action="{% url 'info_display:display_user_info' %}" method="post">
{% csrf_token %}
{{ form.as_ul }}
<input type="submit" value="Request" />
</form>
{% endif %}

{% if downloadfile %}<a href='/info_display/files/pkcs12.pfx' download>Download certificate</a>{% endif %}

<form action="{% url 'info_display:goodbye' %}" method="post">
{% csrf_token %}
<input type="submit" value="Logout" />
</form>

System/Webserver/ca_webserver/info_display/templates/info_display/goodbye.html
<h3>{{info_msg}}</h3>
<a href="/info_display">Back to index</a>

System/Webserver/ca_webserver/info_display/templates/info_display/index.html
<h3>Welcome to the iMovies web interface</h3>

<ul>
  <li><a href="/info_display/user_login">User Login</a></li>
</ul>

System/Webserver/ca_webserver/info_display/templates/info_display/logout.html
{% if error_msg %}<p><strong>{{ error_msg }}</strong></p>{% endif %}

{% if form %}
<form action="{% url 'info_display:wonderland' %}" method="post">
{% csrf_token %}
{{ form.as_ul }}
<input type="submit" value="Query" />
</form>
{% endif %}

System/Webserver/ca_webserver/info_display/templates/info_display/new.html
<h3>Download your new certificate</h3>

{% if error_msg %}<p><strong>{{ error_msg }}</strong></p>{% endif %}
<p>
<a href="/info_display/welcome">Back to welcome</a>
</p>

<form action="{% url 'info_display:new' %}" method="post">
{% csrf_token %}
<input type="submit" value="Download" />
</form>

<form action="{% url 'info_display:goodbye' %}" method="post">
{% csrf_token %}
<input type="submit" value="Logout" />
</form>

System/Webserver/ca_webserver/info_display/templates/info_display/revoke_all.html
<p>If you really want to revoke <i>all</i> your certificates,
  enter your password and click the confirm button.</p>

  {% if error_msg %}<p><strong>{{ error_msg }}</strong></p>{% endif %}

  <p>
  <a href="/info_display/welcome">Back to welcome</a>
</p>

  {% if form %}
  <form action="{% url 'info_display:revoke_all' %}" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Confirm" />
  </form>
  {% endif %}
  <form action="{% url 'info_display:goodbye' %}" method="post">
  {% csrf_token %}
  <input type="submit" value="Logout" />
  </form>

System/Webserver/ca_webserver/info_display/templates/info_display/revoke_single.html
<p>Enter the serial (<u>exactly</u> as in your certificate!) of the certificate
  you want to revoke, enter your password and click the revoke button.</p>

  {% if error_msg %}<p><strong>{{ error_msg }}</strong></p>{% endif %}

  <p>
  <a href="/info_display/welcome">Back to welcome</a>
</p>

  {% if form %}
  <form action="{% url 'info_display:revoke_single' %}" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Revoke" />
  </form>
  {% endif %}
  <form action="{% url 'info_display:goodbye' %}" method="post">
  {% csrf_token %}
  <input type="submit" value="Logout" />
  </form>

System/Webserver/ca_webserver/info_display/templates/info_display/user_login.html
<h3>Login Page</h3>

  {% if error_msg %}<p><strong>{{ error_msg }}</strong></p>{% endif %}

  <form action="{% url 'info_display:user_login' %}" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Login" />
  </form>

System/Webserver/ca_webserver/info_display/templates/info_display/welcome.html
<h3>Welcome {{user_id}}</h3>

  {% if error_msg %}<p><strong>{{ error_msg }}</strong></p>{% endif %}
  {% if error_msg %}<p><strong>Referred here by {{ referrer }}</strong></p>{% endif %}
  <ul>
    <li><a href="/info_display/display_user_info">Get new certificate</a></li>
    <li><a href="/info_display/revoke_single">Revoke single certificate</a></li>
    <li><a href="/info_display/revoke_all">Revoke all certificates</a></li>
    <li><a href="/info_display/crl">Show certificate revocation list</a></li>
  </ul>
  <form action="{% url 'info_display:goodbye' %}" method="post">
  {% csrf_token %}
  <input type="submit" value="Logout" />
  </form>